chore: to bin when gotten numbers

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -11,13 +11,13 @@ jobs:
   check-licenses-readmes-match:
     name: Check licenses match
     runs-on: ubuntu-latest
-    steps: 
+    steps:
       - uses: actions/checkout@v4
       - name: Copy LICENSE to editors/code directory
         run: cp LICENSE editors/code/LICENSE
       - name: Copy README.md to editors/code directory
         run: cp README.md editors/code/README.md
-      - name: Check there is no change 
+      - name: Check there is no change
         run: git diff --quiet || exit 1
   check-versions-match:
     name: Check versions match
@@ -113,3 +113,25 @@ jobs:
         run: cargo clippy --all --all-features -- -D warnings
       - name: Check unused dependencies
         run: cargo machete
+  test_for_performance:
+    name: Test for performance
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install SQLFluff
+        run: pip install sqlfluff
+      - uses: quarylabs/install-sqruff-cli-action@main
+      - run: cd crates/lib/test/fixtures/dialects/ansi
+      - run: pwd
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time sqlfluff lint --dialect ansi --nofail
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time sqlfluff lint --dialect ansi --nofail
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time sqlfluff lint --dialect ansi --nofail
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time (sqruff lint || echo "Command failed with exit code $?")
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time (sqruff lint || echo "Command failed with exit code $?")
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time (sqruff lint || echo "Command failed with exit code $?")
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time sqlfluff lint --dialect ansi select_case_c.sql --nofail
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time sqlfluff lint --dialect ansi select_case_c.sql --nofail
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time sqlfluff lint --dialect ansi select_case_c.sql --nofail
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time (sqruff lint select_case_c.sql || echo "Command failed with exit code $?")
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time (sqruff lint select_case_c.sql || echo "Command failed with exit code $?")
+      - run: cd crates/lib/test/fixtures/dialects/ansi && time (sqruff lint select_case_c.sql || echo "Command failed with exit code $?")
